version: '3.9'

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  neo4j:
    image: neo4j:latest
    container_name: neo4j
    ports:
      - "7474:7474"   # Interface web
      - "7687:7687"   # Bolt protocol
    environment:
      - NEO4J_AUTH=neo4j/test123
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_import:/var/lib/neo4j/import

volumes:
  mongo_data:
  neo4j_data:
  neo4j_logs:
  neo4j_import:
